apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: buildit

resources:
  - namespace.yaml
  - postgres.yaml
  - api.yaml
  - migrations-job.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
